#define wifi_ssid ""
#define wifi_password ""
#define aws_endpoint "xxxxxxxxxx.iot.<region>.amazonaws.com"
#define aws_key "XXXXXXXXXXXXXXXXXXXX"
#define aws_secret "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
#define aws_region "<region>"
#define aws_topic "$aws/things/<Thing>/shadow/update"
